// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tabknoahyyzsrcijsuhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhYmtub2FoeXl6c3JjaWpzdWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzk5MDQsImV4cCI6MjA3MjkxNTkwNH0.mYDps3PvLdPb5ptAyZy5_3S-Lf0P7lDJS1hkWlmEInU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});